{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "88573c0b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import serial\n",
    "import struct\n",
    "import time\n",
    "\n",
    "SERIAL_PORT = '/dev/ttyACM0' \n",
    "BAUD_RATE = 115200\n",
    "\n",
    "# --- YARDIMCI FONKSİYONLAR (Öncekiyle aynı) ---\n",
    "def send_msp_command(ser, cmd, data=[]):\n",
    "    size = len(data)\n",
    "    checksum = size ^ cmd\n",
    "    for b in data: checksum ^= b\n",
    "    header = struct.pack('<3sBB', b'$M<', size, cmd)\n",
    "    ser.write(header + bytes(data) + struct.pack('<B', checksum))\n",
    "\n",
    "def send_rc_commands(ser, roll, pitch, throttle, yaw, aux1, aux2, aux3, aux4):\n",
    "    data = struct.pack('<8H', roll, pitch, throttle, yaw, aux1, aux2, aux3, aux4)\n",
    "    send_msp_command(ser, 200, list(data))\n",
    "\n",
    "def read_radio_switches(ser):\n",
    "    ser.reset_input_buffer()\n",
    "    send_msp_command(ser, 105)\n",
    "    time.sleep(0.02)\n",
    "    if ser.in_waiting >= 6:\n",
    "        if ser.read(3) == b'$M>':\n",
    "            size = ser.read(1)[0]\n",
    "            cmd = ser.read(1)[0]\n",
    "            if cmd == 105:\n",
    "                payload = ser.read(size)\n",
    "                checksum = ser.read(1)[0]\n",
    "                if len(payload) >= 12:\n",
    "                    return struct.unpack('<6H', payload[:12])\n",
    "    return None\n",
    "\n",
    "def read_altitude(ser):\n",
    "    ser.reset_input_buffer()\n",
    "    send_msp_command(ser, 109)\n",
    "    time.sleep(0.02)\n",
    "    if ser.in_waiting >= 6:\n",
    "        if ser.read(3) == b'$M>':\n",
    "            size = ser.read(1)[0]\n",
    "            cmd = ser.read(1)[0]\n",
    "            if cmd == 109:\n",
    "                payload = ser.read(size)\n",
    "                checksum = ser.read(1)[0]\n",
    "                if len(payload) >= 6:\n",
    "                    return struct.unpack('<ih', payload)[0]\n",
    "    return None\n",
    "\n",
    "# --- PID SINIFI ---\n",
    "class AltitudePID:\n",
    "    def __init__(self, Kp, Ki, Kd):\n",
    "        self.Kp = Kp\n",
    "        self.Ki = Ki\n",
    "        self.Kd = Kd\n",
    "        self.prev_error = 0\n",
    "        self.integral = 0\n",
    "        self.last_time = time.time()\n",
    "        \n",
    "    def compute(self, target_altitude, current_altitude):\n",
    "        current_time = time.time()\n",
    "        dt = current_time - self.last_time\n",
    "        if dt <= 0.0: dt = 0.01 \n",
    "        \n",
    "        error = target_altitude - current_altitude\n",
    "        P = self.Kp * error\n",
    "        self.integral += error * dt\n",
    "        self.integral = max(min(self.integral, 50), -50) # Rüzgar birikmesini engelle\n",
    "        I = self.Ki * self.integral\n",
    "        D = self.Kd * ((error - self.prev_error) / dt)\n",
    "        \n",
    "        self.prev_error = error\n",
    "        self.last_time = current_time\n",
    "        return P + I + D\n",
    "\n",
    "# --- ANA GÖREV DÖNGÜSÜ ---\n",
    "try:\n",
    "    ser = serial.Serial(SERIAL_PORT, BAUD_RATE, timeout=0.1)\n",
    "    \n",
    "    # PID Katsayıları\n",
    "    alt_pid = AltitudePID(Kp=1.2, Ki=0.1, Kd=0.5)\n",
    "    \n",
    "    # --- GÖREV PARAMETRELERİ ---\n",
    "    TARGET_ALTITUDE_CM = 200  # 2 Metre!\n",
    "    HOVER_DURATION = 10.0     # 2 metrede kaç saniye asılı kalacak?\n",
    "    \n",
    "    # Rampa (Asansör) Hızları (cm/saniye)\n",
    "    CLIMB_RATE_CM_S = 40.0    # Saniyede 40 cm tırman (2 metreye 5 saniyede çıkar)\n",
    "    DESCEND_RATE_CM_S = 30.0  # Saniyede 30 cm in (Daha yavaş ve güvenli)\n",
    "    \n",
    "    mission_state = \"IDLE\" \n",
    "    hover_start_time = 0\n",
    "    dynamic_target = 0.0      # PID'nin takip edeceği HAREKETLİ hedef\n",
    "    loop_dt = 0.05            # Döngü süresi (20Hz = 0.05 sn)\n",
    "\n",
    "    print(\"\\n--- OTONOM SİSTEM HAZIR ---\")\n",
    "    print(f\"Hedef: {TARGET_ALTITUDE_CM} cm | Bekleme: {HOVER_DURATION} saniye\")\n",
    "    print(\"Kumandadan ARM şalterini kaldırdığınızda otonom kalkış başlayacaktır.\")\n",
    "\n",
    "    while True:\n",
    "        loop_start = time.time()\n",
    "        \n",
    "        radio_data = read_radio_switches(ser)\n",
    "        current_alt = read_altitude(ser)\n",
    "        if current_alt is None: current_alt = 0\n",
    "\n",
    "        if radio_data:\n",
    "            aux1_arm = radio_data[4]\n",
    "            aux2_emg = radio_data[5]\n",
    "            \n",
    "            # ACİL DURUM\n",
    "            if aux2_emg > 1500:\n",
    "                print(\"\\n[!] ACİL DURUM ŞALTERİ ÇEKİLDİ! MOTORLAR SUSTURULUYOR [!]\")\n",
    "                break\n",
    "            \n",
    "            # KUMANDADAN MANUEL İPTAL\n",
    "            if aux1_arm < 1500 and mission_state != \"IDLE\":\n",
    "                print(\"\\n[-] Pilot ARM şalterini indirdi. Görev İptal Edildi!\")\n",
    "                mission_state = \"IDLE\"\n",
    "                send_rc_commands(ser, 1500, 1500, 1000, 1500, 1000, 1000, 1000, 1000)\n",
    "            \n",
    "            # OTONOM GÖREVİ BAŞLAT\n",
    "            elif aux1_arm > 1500 and mission_state == \"IDLE\":\n",
    "                mission_state = \"ARMED_WAIT\"\n",
    "                print(\"\\n[+] ARM edildi. Motorlar rölantide. 2 saniye sonra kalkış başlıyor...\")\n",
    "                time.sleep(2) # Pervanelerin devrini alması için kısa bir bekleme\n",
    "                \n",
    "                mission_state = \"CLIMBING\"\n",
    "                dynamic_target = current_alt # Kalkışa bulunduğumuz yerden başla\n",
    "                alt_pid.integral = 0\n",
    "                print(\"\\n[++] Otonom Kalkış (Yumuşak Rampa) Başladı!\")\n",
    "\n",
    "            # 1. YUMUŞAK YÜKSELİŞ (SOFT TAKEOFF)\n",
    "            if mission_state == \"CLIMBING\":\n",
    "                # Hedefi her döngüde azar azar artır\n",
    "                dynamic_target += CLIMB_RATE_CM_S * loop_dt\n",
    "                if dynamic_target > TARGET_ALTITUDE_CM:\n",
    "                    dynamic_target = TARGET_ALTITUDE_CM\n",
    "                \n",
    "                # PID hareketli hedefi takip eder\n",
    "                pid_out = alt_pid.compute(dynamic_target, current_alt)\n",
    "                throttle_cmd = int(1500 + pid_out)\n",
    "                safe_throttle = max(1400, min(throttle_cmd, 1650))\n",
    "                \n",
    "                send_rc_commands(ser, 1500, 1500, safe_throttle, 1500, 2000, 2000, 1000, 1000)\n",
    "                print(f\"[YÜKSELİYOR] Hedef: {int(dynamic_target)}cm | Gerçek: {current_alt}cm | Motor: {safe_throttle}\")\n",
    "                \n",
    "                # Asıl hedefe vardık mı?\n",
    "                if dynamic_target >= TARGET_ALTITUDE_CM and abs(TARGET_ALTITUDE_CM - current_alt) <= 15:\n",
    "                    mission_state = \"HOVERING\"\n",
    "                    hover_start_time = time.time()\n",
    "                    print(f\"\\n[!] Hedefe Ulaşıldı. {HOVER_DURATION} saniye asılı kalınıyor.\")\n",
    "\n",
    "            # 2. HAVADA ASILI KALMA (HOVER)\n",
    "            elif mission_state == \"HOVERING\":\n",
    "                pid_out = alt_pid.compute(TARGET_ALTITUDE_CM, current_alt)\n",
    "                throttle_cmd = int(1500 + pid_out)\n",
    "                safe_throttle = max(1450, min(throttle_cmd, 1550)) # Hover sırasında motorlar çok agresif tepki vermesin\n",
    "                \n",
    "                send_rc_commands(ser, 1500, 1500, safe_throttle, 1500, 2000, 2000, 1000, 1000)\n",
    "                \n",
    "                if (time.time() - hover_start_time) >= HOVER_DURATION:\n",
    "                    mission_state = \"DESCENDING\"\n",
    "                    dynamic_target = TARGET_ALTITUDE_CM # İniş rampasını yukarıdan başlat\n",
    "                    print(\"\\n[!] Süre doldu. Yumuşak otonom iniş başlıyor...\")\n",
    "\n",
    "            # 3. YUMUŞAK İNİŞ (SOFT LANDING)\n",
    "            elif mission_state == \"DESCENDING\":\n",
    "                # Hedefi her döngüde azar azar azalt\n",
    "                dynamic_target -= DESCEND_RATE_CM_S * loop_dt\n",
    "                if dynamic_target < 0:\n",
    "                    dynamic_target = 0\n",
    "                    \n",
    "                pid_out = alt_pid.compute(dynamic_target, current_alt)\n",
    "                throttle_cmd = int(1500 + pid_out)\n",
    "                safe_throttle = max(1350, min(throttle_cmd, 1550))\n",
    "                \n",
    "                send_rc_commands(ser, 1500, 1500, safe_throttle, 1500, 2000, 2000, 1000, 1000)\n",
    "                print(f\"[İNİYOR] Hedef: {int(dynamic_target)}cm | Gerçek: {current_alt}cm | Motor: {safe_throttle}\")\n",
    "                \n",
    "                # Yere indik mi? (Barometre sapması yüzünden 15 cm'yi yer kabul ediyoruz)\n",
    "                if current_alt <= 15 and dynamic_target <= 10:\n",
    "                    mission_state = \"LANDED\"\n",
    "                    print(\"\\n[+] İniş Başarılı. Motorlar kapatılıyor.\")\n",
    "\n",
    "            # 4. GÖREV BİTİŞİ\n",
    "            elif mission_state == \"LANDED\":\n",
    "                send_rc_commands(ser, 1500, 1500, 1000, 1500, 2000, 1000, 1000, 1000)\n",
    "                # Pilot ARM şalterini indirene kadar kod bekler.\n",
    "\n",
    "        # Döngü zamanlamasını 20Hz'de (0.05s) tutmak için\n",
    "        elapsed = time.time() - loop_start\n",
    "        if elapsed < loop_dt:\n",
    "            time.sleep(loop_dt - elapsed)\n",
    "\n",
    "except KeyboardInterrupt:\n",
    "    print(\"\\n[!] KLAVYEDEN DURDURULDU [!]\")\n",
    "finally:\n",
    "    if 'ser' in locals():\n",
    "        for _ in range(5):\n",
    "            send_rc_commands(ser, 1500, 1500, 1000, 1500, 1000, 1000, 1000, 1000)\n",
    "            time.sleep(0.05)\n",
    "        ser.close()\n",
    "        print(\"Sistem güvenli şekilde kapatıldı.\")"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
